services:

    app:
        container_name: noix-app
        build:
            context: ./../
            dockerfile: ./docker/Dockerfile
        ports:
            - 887:80

    nginx:
        image: nginx:alpine
        container_name: noix-nginx-app
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        depends_on:
            - app
